apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jhqadh5ef-python
  janus-idp.io/tekton: jhqadh5ef-python
  backstage.io/kubernetes-id: jhqadh5ef-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jhqadh5ef-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
